#!/bin/bash
bundle check --path vendor/bundle
if [ $? -eq 0 ]
then
  bin/pumactl start
else
  bundle config build.nokogiri --use-system-libraries
  bundle install --path vendor/bundle --binstubs
  bin/pumactl start
fi
